# Generated by Django 4.2.8 on 2025-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametext', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
    ]
