# Generated by Django 4.2.8 on 2025-07-05 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0002_listpoem_delete_verse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listpoem',
            name='nametext',
        ),
        migrations.RemoveField(
            model_name='listpoem',
            name='text',
        ),
        migrations.AddField(
            model_name='listpoem',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='listpoem',
            name='content',
            field=models.TextField(default=1, verbose_name='Стихотворение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listpoem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listpoem',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
