# Generated by Django 4.2.8 on 2025-07-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verse', '0003_remove_listpoem_nametext_remove_listpoem_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpoem',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listpoem',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
